server:
    port: 8080

spring:
    main:
        banner-mode: "off"
    jpa:
        database: h2
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: update

logging:
    level:
        org:
            springframework: ERROR